name:           Leo J. Leong
description:    "Junior programmer, developer, geeker. Que Sera, Sera!"

markdown:       redcarpet
pygments:       true
logo:           false

url:            http://leoleong.github.io
author:         Leo J. Leong
bio:            "Junior programmer, developer, geeker."

github:         leoleong
twitter:        _leoleong
